name: Build React

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'  
          cache-dependency-path: 'react-jobs/package-lock.json'

      - name: Install Dependencies
        run: npm install
        working-directory: './react-jobs'

      - name: Build React Package
        run: npm run build  
        working-directory: './react-jobs'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./react-jobs/build
